services:
  app:
    image: binarygalen/express-app:latest
    ports:
      - "8080:8080"
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.41 
    command: --interval 30
    restart: always